tm_website/tm_website/tm_main/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views


app_name = 'tm_main'

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
        url(r'^signup/$', views.signup, name='signup'),
        url(r'^tasks/$', views.show_tasks, name='show_tasks'),
        url(r'^tasks/(?P<task_id>[0-9]+)/$', views.edit_task, name='edit_task'),
        url(r'^tasks/(?P<task_id>[0-9]+)/remove$', views.task_remove, name='remove_task'),
        url(r'^tasks/(?P<task_id>[0-9]+)/scriptadd', views.script_add, name='add_script'),
        url(r'^tasks/(?P<task_id>[0-9]+)/scriptremove', views.script_remove, name='remove_script'),
        url(r'^tasks/(?P<ownertask_id>[0-9]+)/subtaskadd$', views.subtask_add, name='remove_task'),
        url(r'^tasks/(?P<task_id>[0-9]+)/useradd/$', views.add_tasks_user, name='add_user'),
        url(r'^tasks/(?P<task_id>[0-9]+)/userremove/(?P<subuser_id>[0-9]+)$',
            views.remove_tasks_user, name='remove_user'),
        url(r'^tasks/(?P<task_id>[0-9]+)/status/(?P<status_name>\w+)$', views.status_change, name='change_status'),
        url(r'^users/$', views.show_users, name='show_users'),
        url(r'^users/edit$', views.edit_myself, name='edit_myself'),
        url(r'^help/$', views.help, name='help'),
        url(r'^links/$', views.links, name='links'),
]

tm_website/tm_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('tm_website.tm_main.urls')),
    url(r'^admin/', admin.site.urls),
]

tm_website/tm_website/tm_main/models.py
from django.db import models

# Create your models here.

tm_website/tm_website/tm_main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime
from tempus_dominus.widgets import DateTimePicker


class UserAuthorizationForm(forms.Form):

    username = forms.CharField(max_length=24, required=True)
    password = forms.CharField(max_length=24, required=True)


class UserEditForm(forms.Form):

    id = forms.IntegerField(required=True)
    first_name = forms.CharField(max_length=128, required=False)
    last_name = forms.CharField(max_length=128, required=False)
    email = forms.EmailField(max_length=128, required=False)


class TaskEditForm(forms.Form):

    id = forms.IntegerField(required=True)
    name = forms.CharField(max_length=24, required=False)
    description = forms.CharField(max_length=250, required=False)
    #start_datetime = forms.DateTimeField(required=False, input_formats=['%d/%m/%Y %H:%M'], widget=DateTimePicker(options={'format':  'YYYY-MM-DD'}))
    start_datetime = forms.DateTimeField(required=False, input_formats=['%d.%m.%Y %H:%M', '%d/%m/%Y %H:%M',
                                                                        '%d.%m.%Y %H-%M', '%d/%m/%Y %H-%M'],
                                         widget=DateTimePicker())
    end_datetime = forms.DateTimeField(required=False, input_formats=['%d.%m.%Y %H:%M', '%d/%m/%Y %H:%M',
                                                                      '%d.%m.%Y %H-%M', '%d/%m/%Y %H-%M'])

    ownertask_id = forms.IntegerField(required=False)

    script_id = forms.IntegerField(required=False)
    days_delta = forms.IntegerField(required=False)


class SubuserAddForm(forms.Form):

    user_info = forms.CharField (max_length=24, required=True)


class TaskRemoveForm(forms.Form):

    id = forms.IntegerField(required=True)


class StatusChangeForm(forms.Form):

    task_id = forms.IntegerField(required=True)
    status = forms.CharField(required=True)


class TaskSortForm(forms.Form):

    show_active = forms.BooleanField(required=False)
    show_inactive = forms.BooleanField(required=False)
    show_stopped = forms.BooleanField(required=False)
    show_completed = forms.BooleanField(required=False)
    show_overdue = forms.BooleanField(required=False)

    sort_mode = forms.CharField(required=False)

tm_website/tm_website/tm_main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, RequestContext
from django.contrib import auth
from django.shortcuts import render
from django.contrib.auth import login, authenticate

from .forms import (UserAuthorizationForm,
                    UserEditForm,
                    TaskEditForm,
                    SubuserAddForm,
                    TaskSortForm)
from .decorators import tm_main_decorator

from django.contrib.auth.forms import UserCreationForm
from datetime import datetime
import pytz

from tm_core.control.core_interface import CoreInterface
from tm_core.control.inspector import Inspector


def index(request):
    return render(request, 'tm_main/index.html')


def authorization(request):
    if request.method == 'POST':
        form = UserAuthorizationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            return render(request, 'tm_main/index.html')

    else:
        form = UserAuthorizationForm()
    return render(request, 'registration/login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')

            CoreInterface.user_add(input_login=username, input_password=raw_password)

            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request, 'tm_main/index.html')

    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@tm_main_decorator
def show_tasks(request):
    CoreInterface.perform(0)
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    tasks_info = CoreInterface.get_tasks_info(user_id)

    if request.method == 'GET':

        show_active = True
        show_inactive = True
        show_stopped = True
        show_completed = True
        show_overdue = True
        sort_mode = 'No sort'

        if 'show_button' in request.GET:
            show_buttons_list = request.GET.getlist('show_button', None)
            if 'show_active' in show_buttons_list:
                show_active = True
            else:
                show_active = False
            if 'show_inactive' in show_buttons_list:
                show_inactive = True
            else:
                show_inactive = False
            if 'show_stopped' in show_buttons_list:
                show_stopped = True
            else:
                show_stopped = False
            if 'show_completed' in show_buttons_list:
                show_completed = True
            else:
                show_completed = False
            if 'show_overdue' in show_buttons_list:
                show_overdue = True
            else:
                show_overdue = False

        if 'sort_mode' in request.GET:
            sort_mode = request.GET['sort_mode']

        if sort_mode == 'Sort by name':
            tasks_info.sort(key=lambda i: i['name'])
        elif sort_mode == 'Sort by id':
            tasks_info.sort(key=lambda i: i['id'])
        elif sort_mode == 'Sort by status':
                tasks_info.sort(key=lambda i: i['status'])

        tasks_to_remove = []
        if not show_active:
            for task in tasks_info:
                if task['status'] == 'ACTIVE':
                    tasks_to_remove.append(task)
        if not show_inactive:
            for task in tasks_info:
                if task['status'] == 'INACTIVE':
                    tasks_to_remove.append(task)
        if not show_stopped:
            for task in tasks_info:
                if task['status'] == 'STOPPED':
                    tasks_to_remove.append(task)
        if not show_completed:
            for task in tasks_info:
                if task['status'] == 'COMPLETED':
                    tasks_to_remove.append(task)
        if not show_overdue:
            for task in tasks_info:
                if task['status'] == 'OVERDUE':
                    tasks_to_remove.append(task)
        print(tasks_to_remove)
        for task in tasks_to_remove:
            if task in tasks_info:
                tasks_info.remove(task)

        context = {'show_active': show_active, 'show_inactive': show_inactive, 'show_stopped': show_stopped,
                   'show_completed': show_completed, 'show_overdue': show_overdue, 'sort_mode': sort_mode,
                   'tasks_info': tasks_info}
        return render(request, 'tm_main/task/show_tasks.html', context)

    return HttpResponseRedirect('/')


@tm_main_decorator
def edit_task(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    if request.method == 'POST':

        form = TaskEditForm(request.POST)
        user_form = SubuserAddForm(request.POST)
        if form.is_valid():

            task_id = form.cleaned_data.get('id')
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            start_datetime = form.cleaned_data.get('start_datetime')
            end_datetime = form.cleaned_data.get('end_datetime')
            script_id = form.cleaned_data.get('script_id')
            days_delta = form.cleaned_data.get('days_delta')

            if start_datetime is not None:
                start_datetime = start_datetime.replace(tzinfo=None)
            if end_datetime is not None:
                end_datetime = end_datetime.replace(tzinfo=None)

            if task_id == 0:
                CoreInterface.task_add(user_id, user_id, name, description, start_datetime, end_datetime)
            else:
                CoreInterface.task_edit(user_id, task_id, name, description, start_datetime, end_datetime)

            if script_id is not None:
                CoreInterface.script_change(user_id, task_id, name, description, days_delta, None, days_delta, None,
                                            True, None, None)

            return HttpResponseRedirect('/tasks/')

        task_info = CoreInterface.get_task_info(user_id, form.cleaned_data.get('id'))
        subtasks_info = CoreInterface.get_subtasks_info(task_info['id'])
        ownertask_info = None
        if task_info['ownertask_id'] is not None:
            ownertask_info = CoreInterface.get_task_info(user_id, task_info['ownertask_id'])

        context = {'form': form, 'users': task_info['users'], 'user_form': user_form, 'subtasks_info': subtasks_info,
                   'ownertask_info': ownertask_info}

    else:
        if task_id != '0' and task_id != 0:
            task_info = CoreInterface.get_task_info(user_id, task_id)

            # Collecting subtasks and ownertask info
            subtasks_info = CoreInterface.get_subtasks_info(task_info['id'])
            ownertask_info = None
            if task_info['ownertask_id'] is not None:
                ownertask_info = CoreInterface.get_task_info(user_id, task_info['ownertask_id'])

            # Collecting script info
            days_delta = 1
            if task_info['script_id'] is not None:
                script_info = CoreInterface.get_script_info(user_id, task_info['script_id'])
                if script_info['start_static_delta'] is not None:
                    days_delta = script_info['start_static_delta']
                if script_info['end_static_delta'] is not None:
                    days_delta = script_info['end_static_delta']

            # Creating forms
            form = TaskEditForm(initial={'id': task_info['id'], 'name': task_info['name'],
                                         'description': task_info['description'],
                                         'start_datetime': task_info['start_datetime'],
                                         'end_datetime': task_info['end_datetime'],
                                         'ownertask_id': task_info['ownertask_id'],
                                         'script_id': task_info['script_id'],
                                         'days_delta': days_delta})
            user_form = SubuserAddForm()

            context = {'form': form, 'users': task_info['users'], 'user_form': user_form,
                       'subtasks_info': subtasks_info, 'ownertask_info': ownertask_info}

        else:
            form = TaskEditForm(initial={'id': 0, 'name': 'NewName', 'description': '',
                                         'ownertask_id': None, 'script_id': None})
            context = {'form': form}

    return render(request, 'tm_main/task/edit_task.html', context)


@tm_main_decorator
def task_remove(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    CoreInterface.task_remove(user_id, task_id)

    return HttpResponseRedirect('/tasks/')


@tm_main_decorator
def script_add(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    task_info = CoreInterface.get_task_info(user_id, task_id)
    CoreInterface.script_change(user_id, task_id, task_info['name'], task_info['description'], 1, None, 1, None, True,
                                ['COMPLETED', 'OVERDUE'], None)

    return HttpResponseRedirect('/tasks/{task_id}'.format(task_id=task_id))


@tm_main_decorator
def script_remove(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    CoreInterface.script_remove(user_id, task_id)

    return HttpResponseRedirect('/tasks/{task_id}'.format(task_id=task_id))


@tm_main_decorator
def add_tasks_user(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    if request.method == 'POST':

tm_website/tm_website/tm_main/templates/tm_main/basic_template.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'tm_main/css/bootstrap.min.css' %}">
    <!-- Basic template CSS -->
    <link rel="stylesheet" href="{% static 'tm_main/css/basic_template.css' %}">
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block scripts %}
    {% endblock %}

    <title>Task manager</title>
  </head>
  <body>

    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'tm_main:index' %}">Task manager</a>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'tm_main:logout' %}">Log out</a>
          {% else %}
            <a class="nav-link" href="{% url 'tm_main:login' %}">Log in</a>
          {% endif %}
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Tasks</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="file"></span>
              </a>
            </h6>
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tm_main:show_tasks' %}">
                  Show tasks
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Users</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="users"></span>
              </a>
            </h6>
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tm_main:show_users' %}">
                  Show all users
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tm_main:edit_myself' %}">
                  Edit my user
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Additional</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="file-text"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tm_main:help' %}">
                  How to use
                </a>
              </li>
              <li class="nav">
                <a class="nav-link" href="{% url 'tm_main:links' %}">
                  Links
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <!--<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">-->
          <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 justify-content-center">
            {% block main_content %}
            {% endblock %}
          </div>
        </main>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static 'tm_main/js/bootstrap.min.js' %}"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

  </body>
</html>

tm_website/tm_website/tm_main/templates/tm_main/help.html
{% extends 'tm_main/basic_template.html' %}
{% load staticfiles %}

{% block main_content %}
  <h1>Description here.</h1>
{% endblock %}

tm_website/tm_website/tm_main/templates/tm_main/index.html
{% extends 'tm_main/basic_template.html' %}

{% block main_content %}
  {% if user.is_authenticated %}
    <h1>Index page here.</h1>
  {% else %}
    <h1>Please</h1><h1>
    <a class="nav-link" href="{% url 'tm_main:login' %}">log in</a></h1>
    <h1> to see page content.</h1>
  {% endif %}
{% endblock %}

tm_website/tm_website/tm_main/templates/tm_main/links.html
{% extends 'tm_main/basic_template.html' %}
{% load staticfiles %}

{% block main_content %}
  <h1>Links here.</h1>
{% endblock %}