tm_website/tm_website/tm_main/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views


app_name = 'tm_main'

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
        url(r'^signup/$', views.signup, name='signup'),
        url(r'^tasks/$', views.show_tasks, name='show_tasks'),
        url(r'^tasks/(?P<task_id>[0-9]+)/$', views.edit_task, name='edit_task'),
        url(r'^tasks/(?P<task_id>[0-9]+)/remove$', views.task_remove, name='remove_task'),
        url(r'^tasks/(?P<task_id>[0-9]+)/scriptadd', views.script_add, name='add_script'),
        url(r'^tasks/(?P<task_id>[0-9]+)/scriptremove', views.script_remove, name='remove_script'),
        url(r'^tasks/(?P<ownertask_id>[0-9]+)/subtaskadd$', views.subtask_add, name='remove_task'),
        url(r'^tasks/(?P<task_id>[0-9]+)/useradd/$', views.add_tasks_user, name='add_user'),
        url(r'^tasks/(?P<task_id>[0-9]+)/userremove/(?P<subuser_id>[0-9]+)$',
            views.remove_tasks_user, name='remove_user'),
        url(r'^tasks/(?P<task_id>[0-9]+)/status/(?P<status_name>\w+)$', views.status_change, name='change_status'),
        url(r'^users/$', views.show_users, name='show_users'),
        url(r'^users/edit$', views.edit_myself, name='edit_myself'),
        url(r'^help/$', views.help, name='help'),
        url(r'^links/$', views.links, name='links'),
]

tm_website/tm_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('tm_website.tm_main.urls')),
    url(r'^admin/', admin.site.urls),
]

tm_website/tm_website/tm_main/models.py
from django.db import models

# Create your models here.

tm_website/tm_website/tm_main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime
from tempus_dominus.widgets import DateTimePicker


class UserAuthorizationForm(forms.Form):

    username = forms.CharField(max_length=24, required=True)
    password = forms.CharField(max_length=24, required=True)


class UserEditForm(forms.Form):

    id = forms.IntegerField(required=True)
    first_name = forms.CharField(max_length=128, required=False)
    last_name = forms.CharField(max_length=128, required=False)
    email = forms.EmailField(max_length=128, required=False)


class TaskEditForm(forms.Form):

    id = forms.IntegerField(required=True)
    name = forms.CharField(max_length=24, required=False)
    description = forms.CharField(max_length=250, required=False)
    #start_datetime = forms.DateTimeField(required=False, input_formats=['%d/%m/%Y %H:%M'], widget=DateTimePicker(options={'format':  'YYYY-MM-DD'}))
    start_datetime = forms.DateTimeField(required=False, input_formats=['%d.%m.%Y %H:%M', '%d/%m/%Y %H:%M',
                                                                        '%d.%m.%Y %H-%M', '%d/%m/%Y %H-%M'],
                                         widget=DateTimePicker())
    end_datetime = forms.DateTimeField(required=False, input_formats=['%d.%m.%Y %H:%M', '%d/%m/%Y %H:%M',
                                                                      '%d.%m.%Y %H-%M', '%d/%m/%Y %H-%M'])

    ownertask_id = forms.IntegerField(required=False)

    script_id = forms.IntegerField(required=False)
    days_delta = forms.IntegerField(required=False)


class SubuserAddForm(forms.Form):

    user_info = forms.CharField (max_length=24, required=True)


class TaskRemoveForm(forms.Form):

    id = forms.IntegerField(required=True)


class StatusChangeForm(forms.Form):

    task_id = forms.IntegerField(required=True)
    status = forms.CharField(required=True)


class TaskSortForm(forms.Form):

    show_active = forms.BooleanField(required=False)
    show_inactive = forms.BooleanField(required=False)
    show_stopped = forms.BooleanField(required=False)
    show_completed = forms.BooleanField(required=False)
    show_overdue = forms.BooleanField(required=False)

    sort_mode = forms.CharField(required=False)

tm_website/tm_website/tm_main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, RequestContext
from django.contrib import auth
from django.shortcuts import render
from django.contrib.auth import login, authenticate

from .forms import (UserAuthorizationForm,
                    UserEditForm,
                    TaskEditForm,
                    SubuserAddForm,
                    TaskSortForm)
from .decorators import tm_main_decorator

from django.contrib.auth.forms import UserCreationForm
from datetime import datetime
import pytz

from tm_core.control.core_interface import CoreInterface
from tm_core.control.inspector import Inspector


def index(request):
    return render(request, 'tm_main/index.html')


def authorization(request):
    if request.method == 'POST':
        form = UserAuthorizationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            return render(request, 'tm_main/index.html')

    else:
        form = UserAuthorizationForm()
    return render(request, 'registration/login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')

            CoreInterface.user_add(input_login=username, input_password=raw_password)

            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request, 'tm_main/index.html')

    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@tm_main_decorator
def show_tasks(request):
    CoreInterface.perform(0)
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    tasks_info = CoreInterface.get_tasks_info(user_id)

    if request.method == 'GET':

        show_active = True
        show_inactive = True
        show_stopped = True
        show_completed = True
        show_overdue = True
        sort_mode = 'No sort'

        if 'show_button' in request.GET:
            show_buttons_list = request.GET.getlist('show_button', None)
            if 'show_active' in show_buttons_list:
                show_active = True
            else:
                show_active = False
            if 'show_inactive' in show_buttons_list:
                show_inactive = True
            else:
                show_inactive = False
            if 'show_stopped' in show_buttons_list:
                show_stopped = True
            else:
                show_stopped = False
            if 'show_completed' in show_buttons_list:
                show_completed = True
            else:
                show_completed = False
            if 'show_overdue' in show_buttons_list:
                show_overdue = True
            else:
                show_overdue = False

        if 'sort_mode' in request.GET:
            sort_mode = request.GET['sort_mode']

        if sort_mode == 'Sort by name':
            tasks_info.sort(key=lambda i: i['name'])
        elif sort_mode == 'Sort by id':
            tasks_info.sort(key=lambda i: i['id'])
        elif sort_mode == 'Sort by status':
                tasks_info.sort(key=lambda i: i['status'])

        tasks_to_remove = []
        if not show_active:
            for task in tasks_info:
                if task['status'] == 'ACTIVE':
                    tasks_to_remove.append(task)
        if not show_inactive:
            for task in tasks_info:
                if task['status'] == 'INACTIVE':
                    tasks_to_remove.append(task)
        if not show_stopped:
            for task in tasks_info:
                if task['status'] == 'STOPPED':
                    tasks_to_remove.append(task)
        if not show_completed:
            for task in tasks_info:
                if task['status'] == 'COMPLETED':
                    tasks_to_remove.append(task)
        if not show_overdue:
            for task in tasks_info:
                if task['status'] == 'OVERDUE':
                    tasks_to_remove.append(task)
        print(tasks_to_remove)
        for task in tasks_to_remove:
            if task in tasks_info:
                tasks_info.remove(task)

        context = {'show_active': show_active, 'show_inactive': show_inactive, 'show_stopped': show_stopped,
                   'show_completed': show_completed, 'show_overdue': show_overdue, 'sort_mode': sort_mode,
                   'tasks_info': tasks_info}
        return render(request, 'tm_main/task/show_tasks.html', context)

    return HttpResponseRedirect('/')


@tm_main_decorator
def edit_task(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    if request.method == 'POST':

        form = TaskEditForm(request.POST)
        user_form = SubuserAddForm(request.POST)
        if form.is_valid():

            task_id = form.cleaned_data.get('id')
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            start_datetime = form.cleaned_data.get('start_datetime')
            end_datetime = form.cleaned_data.get('end_datetime')
            script_id = form.cleaned_data.get('script_id')
            days_delta = form.cleaned_data.get('days_delta')

            if start_datetime is not None:
                start_datetime = start_datetime.replace(tzinfo=None)
            if end_datetime is not None:
                end_datetime = end_datetime.replace(tzinfo=None)

            if task_id == 0:
                CoreInterface.task_add(user_id, user_id, name, description, start_datetime, end_datetime)
            else:
                CoreInterface.task_edit(user_id, task_id, name, description, start_datetime, end_datetime)

            if script_id is not None:
                CoreInterface.script_change(user_id, task_id, name, description, days_delta, None, days_delta, None,
                                            True, None, None)

            return HttpResponseRedirect('/tasks/')

        task_info = CoreInterface.get_task_info(user_id, form.cleaned_data.get('id'))
        subtasks_info = CoreInterface.get_subtasks_info(task_info['id'])
        ownertask_info = None
        if task_info['ownertask_id'] is not None:
            ownertask_info = CoreInterface.get_task_info(user_id, task_info['ownertask_id'])

        context = {'form': form, 'users': task_info['users'], 'user_form': user_form, 'subtasks_info': subtasks_info,
                   'ownertask_info': ownertask_info}

    else:
        if task_id != '0' and task_id != 0:
            task_info = CoreInterface.get_task_info(user_id, task_id)

            # Collecting subtasks and ownertask info
            subtasks_info = CoreInterface.get_subtasks_info(task_info['id'])
            ownertask_info = None
            if task_info['ownertask_id'] is not None:
                ownertask_info = CoreInterface.get_task_info(user_id, task_info['ownertask_id'])

            # Collecting script info
            days_delta = 1
            if task_info['script_id'] is not None:
                script_info = CoreInterface.get_script_info(user_id, task_info['script_id'])
                if script_info['start_static_delta'] is not None:
                    days_delta = script_info['start_static_delta']
                if script_info['end_static_delta'] is not None:
                    days_delta = script_info['end_static_delta']

            # Creating forms
            form = TaskEditForm(initial={'id': task_info['id'], 'name': task_info['name'],
                                         'description': task_info['description'],
                                         'start_datetime': task_info['start_datetime'],
                                         'end_datetime': task_info['end_datetime'],
                                         'ownertask_id': task_info['ownertask_id'],
                                         'script_id': task_info['script_id'],
                                         'days_delta': days_delta})
            user_form = SubuserAddForm()

            context = {'form': form, 'users': task_info['users'], 'user_form': user_form,
                       'subtasks_info': subtasks_info, 'ownertask_info': ownertask_info}

        else:
            form = TaskEditForm(initial={'id': 0, 'name': 'NewName', 'description': '',
                                         'ownertask_id': None, 'script_id': None})
            context = {'form': form}

    return render(request, 'tm_main/task/edit_task.html', context)


@tm_main_decorator
def task_remove(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    CoreInterface.task_remove(user_id, task_id)

    return HttpResponseRedirect('/tasks/')


@tm_main_decorator
def script_add(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    task_info = CoreInterface.get_task_info(user_id, task_id)
    CoreInterface.script_change(user_id, task_id, task_info['name'], task_info['description'], 1, None, 1, None, True,
                                ['COMPLETED', 'OVERDUE'], None)

    return HttpResponseRedirect('/tasks/{task_id}'.format(task_id=task_id))


@tm_main_decorator
def script_remove(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    CoreInterface.script_remove(user_id, task_id)

    return HttpResponseRedirect('/tasks/{task_id}'.format(task_id=task_id))


@tm_main_decorator
def add_tasks_user(request, task_id):
    user_id = CoreInterface.get_user_id(auth.get_user(request).get_username())
    if request.method == 'POST':

tm_website/tm_website/tm_main/templates/tm_main/task/edit_task.html
{% extends 'tm_main/basic_template.html' %}
{% load staticfiles %}

{% block scripts %}
  <script crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  {{ form.media }}
{% endblock %}

{% block main_content %}
  <div class="col-md-8 order-md-1">
    <h1 class="mb-3">Editing task</h1>
    <hr class="mb-4">

    <form class="needs-validation col-12" id="UserAddForm" method="post" action="{% url 'tm_main:add_user' form.id.value %}">{% csrf_token %}</form>

    <form class="needs-validation" method="post" action="{% url 'tm_main:edit_task' form.id.value %}">

      {% csrf_token %}

      <div class="row">
        <div class="col-md-10 mb-3">
          <label for="name">Name <span class="text-muted">(Optional)</span></label>
          <input class="form-control" name="name" id="name" type="text" value="{% if form.name.value != None %}{{form.name.value}}{% endif %}">
        </div>
        <div class="col-md-2 mb-3">
          <label for="id">Id</label>
          <input readonly class="form-control" name="id" id="id" type="text" value="{{form.id.value}}">
        </div>
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" name="description" id="description" maxlength="250">{% if form.description.value != None %}{{form.description.value}}{% endif %}</textarea>
      </div>

      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="start_datetime">Start datetime <span class="text-muted">(Optional)</span></label>
          <input class="form-control datetimepicker-input" id="start_datetime" name="start_datetime" type="datetime-local" value="{% if form.start_datetime.value != None %}{{form.start_datetime.value|date:'d.m.Y H:i'}}{% endif %}">
        </div>
        <div class="col-md-6 mb-3">
          <label for="end_datetime">End datetime <span class="text-muted">(Optional)</span></label>
          <input class="form-control datetimepicker-input" id="end_datetime" name="end_datetime" type="datetime-local" value="{% if form.end_datetime.value != None %}{{form.end_datetime.value|date:'d.m.Y H:i'}}{% endif %}">
        </div>
      </div>

      {% if form.id.value != 0 %}

      <hr class="mb-4">

      <h4 class="d-flex justify-content-between align-items-center mb-3 text-black">Users</h4>
      <div class="row">
        {% for user in users %}
          <div class="col-xl-3">
            <div class="card mb-3">
              <div class="card-body">
                <p class="card-text text-lg">Login: {{user.login}}</p>
                <p class="card-text text-muted">id: {{user.id}}</p>
                <button type="button" class="btn btn-sm" onclick="location.href='/tasks/{{form.id.value}}/userremove/{{user.id}}'">Remove</button>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <div>
        <label for="user_info">Enter user login or id to add user</label>
        <input class="form-control" id="user_info" name="user_info" type="text" form="UserAddForm">
        <canvas height="10"></canvas>
        <button class="btn btn-outline-secondary btn-lg btn-block" form="UserAddForm">Add subuser</button>
      </div>

      <hr class="mb-4">

      <!--<div class="row">
        <div class="col-md-6 mb-3">
          <label for="start_datetime">Start datetime <span class="text-muted">(Optional)</span></label>
          <input class="form-control datetimepicker-input" id="start_datetime" name="start_datetime" type="datetime-local" value="{{form.start_datetime.value}}" data-toggle="datetimepicker" data-target="#start_datetime">
          {{ form.start_datetime}}
          <div class="invalid-feedback">
            Wrong datetime.
          </div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="end_datetime">End datetime <span class="text-muted">(Optional)</span></label for="end_datetime">
          <input class="form-control datetimepicker-input" id="end_datetime" name="end_datetime" type="datetime-local" value="{{form.end_datetime.value}}" data-toggle="datetimepicker" data-target="#end_datetime">
          <div class="invalid-feedback">
            Wrong datetime.
          </div>
        </div>
      </div>-->

      {% if form.ownertask_id.value == None and form.script_id.value == None and subtasks_info|length == 0 %}

        <a class="btn btn-outline-secondary btn-lg btn-block" onclick="location.href='/tasks/{{form.id.value}}/subtaskadd'">Add subtask</a>

        {% if form.start_datetime.value != None and form.end_datetime.value != None %}
        <a class="btn btn-outline-secondary btn-lg btn-block" onclick="location.href='/tasks/{{form.id.value}}/scriptadd'">Make periodical</a>
        {% endif %}

      {% elif form.script_id.value == None %}

        {% if form.ownertask_id.value != None %}
          <div class="col-md-12">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
              <span class="text-black">Ownertask</span>
            </h4>
            <ul class="list-group mb-3">
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">{{ownertask_info.name}}</h6>
                  <small class="text-muted">{{ownertask_info.description}}</small>
                </div>
                <span class="text-muted">Id: {{ownertask_info.id}}</span>
              </li>
              <a class="btn btn-sm btn-secondary" onclick="location.href='/tasks/{{ownertask_info.id}}'">Edit</a>
            </ul>
          </div>
        {% endif %}

        <div class="col-md-12">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-black">Subtasks</span>
            <span class="badge badge-secondary badge-pill">{{subtasks_info|length}}</span>
          </h4>
          <ul class="list-group mb-3">
            {% for subtask in subtasks_info %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{subtask.name}}</h6>
                <small class="text-muted">{{subtask.description}}</small>
              </div>
              <span class="text-muted">Id: {{subtask.id}}</span>
            </li>
            <div class="btn-group">
                <a class="btn btn-sm btn-outline-secondary btn-block" onclick="location.href='/tasks/{{subtask.id}}'">Edit</a>
                <a class="btn btn-sm btn-secondary" onclick="location.href='/tasks/{{subtask.id}}/remove'">Remove</a>
            </div>
            {% endfor %}
          </ul>
        </div>
        <a class="btn btn-outline-secondary btn-lg btn-block" onclick="location.href='/tasks/{{form.id.value}}/subtaskadd'">Add subtask</a>

      {% else %}

        <h2 class="mb-3">Periodical settings</h2>
        <div class="row justify-content-center">
          <div class="col-md-3 mb-3">
            <label for="days_delta">Repeat every * days</label>
            <input class="form-control" name="days_delta" id="days_delta" type="number" min="1" value="{{form.days_delta.value}}" required>
          </div>
          <div class="col-md-2 mb-3">
            <label for="script_id">Id</label>
            <input readonly class="form-control" name="script_id" id="script_id" type="text" value="{{form.script_id.value}}">
          </div>
        </div>
        <a class="btn btn-outline-secondary btn-lg btn-block" onclick="location.href='/tasks/{{form.id.value}}/scriptremove'">Remove periodicity</a>

      {% endif %}
      {% endif %}

      <hr class="mb-4">

      <button class="btn btn-primary btn-lg btn-block" type="submit">
        {% if form.id.value == 0 %}
          Add
        {% else %}
          Edit
        {% endif %}
      </button>
      <a class="btn btn-primary btn-lg btn-block" onclick="location.href='/tasks/{{form.id.value}}/remove'">Remove</a>
    </form>

    {% for e in form.non_field_errors %}
      <div class="alert alert-danger">{{e}}</div>
    {% endfor %}

  </div>
{% endblock %}

tm_website/tm_website/tm_main/templates/tm_main/task/show_tasks.html
{% extends 'tm_main/basic_template.html' %}

{% block main_content %}
  <div class="album py-5 col-10">
    <h1 class="mb-3">Tasks list</h1>
    <hr class="mb-4">

    <form id="form" name="form" method="get" action="{% url 'tm_main:show_tasks'%}" novalidate>
        {% csrf_token %}

        <div class="btn-group d-flex justify-content-center">
          <input type="submit" name="sort_mode" class="btn btn-secondary col-3" value="No sort">
          <input type="submit" name="sort_mode" class="btn btn-secondary col-3" value="Sort by name">
          <input type="submit" name="sort_mode" class="btn btn-secondary col-3" value="Sort by id">
          <input type="submit" name="sort_mode" class="btn btn-secondary col-3" value="Sort by status">
        </div>

        <canvas height="20"></canvas>

        <div class="btn-group-toggle d-flex justify-content-around" data-toggle="buttons">
          <label class="btn btn-outline-info {% if show_active %}active{% endif %} col-2">
            <input name="show_button" id="show_active" type="checkbox" value="show_active" {% if show_active %}checked{% endif %} onchange="submit_form()"> ACTIVE
          </label>
          <label class="btn btn-outline-secondary {% if show_inactive %}active{% endif %} col-2">
            <input name="show_button" id="show_inactive" type="checkbox" value="show_inactive" {% if show_inactive %}checked{% endif %} onchange="submit_form()"> INACTIVE
          </label>
          <label class="btn btn-outline-dark {% if show_stopped %}active{% endif %} col-2">
            <input name="show_button" id="show_stopped" type="checkbox" value="show_stopped" {% if show_stopped %}checked{% endif %} onchange="submit_form()"> STOPPED
          </label>
          <label class="btn btn-outline-success {% if show_completed %}active{% endif %} col-2">
            <input name="show_button" id="show_completed" type="checkbox" value="show_completed" {% if show_completed %}checked{% endif %} onchange="submit_form()"> COMPLETED
          </label>
          <label class="btn btn-outline-danger {% if show_overdue %}active{% endif %} col-2">
            <input name="show_button" id="show_overdue" type="checkbox" value="show_overdue" {% if show_overdue %}checked{% endif %} onchange="submit_form()"> OVERDUE
          </label>
        </div>
    </form>

    <hr class="mb-4">
    <button type="button" class="btn btn-lg col-12" onclick="location.href='/tasks/0'">Add</button>
    <canvas height="20"></canvas>
    <div class="container col-12">
      <div class="row">

        {% for task in tasks_info %}
          <div class="col-xl-6">
            <div class="card mb-4 shadow-sm">
              {% if task.status == 'ACTIVE' %}
              <div class="card-body" style="background:white">
              {% elif task.status == 'INACTIVE' or task.status == 'STOPPED' %}
              <div class="card-body" style="background:#464a464d">
              {% elif task.status == 'COMPLETED' %}
              <div class="card-body" style="background:#73e36c1a">
              {% else %}
              <div class="card-body" style="background:#e428391a">
              {% endif %}
                <div class="row justify-content-center">
                  <h2>{{task.name}}</h2>
                </div>
                <p class="card-text">{{task.description}}</p>
                <div class="row justify-content-between">
                  <p class="card-text ml-2">Status: {{task.status}}</p>
                  <p class="card-text mr-2">Id: {{task.id}}</p>
                </div>
                <div class="row justify-content-between">
                  <p class="card-text text-muted small ml-2">Start: {{task.start_datetime}}</p>
                  <p class="card-text text-muted small mr-2">End: {{task.end_datetime}}</p>
                </div>
                <div class="d-flex justify-content-between align-items-center">

                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-success" onclick="location.href='/tasks/{{task.id}}/status/COMPLETED'">Complete</button>
                    {% if task.status != 'COMPLETED' and task.status != 'OVERDUE' and task.status != 'INACTIVE' %}
                        {% if task.status == 'STOPPED' %}
                          <button type="button" class="btn btn-sm btn-outline-info" onclick="location.href='/tasks/{{task.id}}/status/ACTIVE'">Resume</button>
                        {% else %}
                          <button type="button" class="btn btn-sm btn-outline-dark" onclick="location.href='/tasks/{{task.id}}/status/STOPPED'">Stop</button>
                        {% endif %}
                    {% endif %}
                    <button type="button" class="btn btn-sm btn-outline-danger" onclick="location.href='/tasks/{{task.id}}/status/OVERDUE'">Overdue</button>
                  </div>

                  <div class="btn-group">
                    <button type="button" class="btn btn-light" onclick="location.href='/tasks/{{task.id}}'">Show|Edit</button>
                    <button type="button" class="btn btn-light" onclick="location.href='/tasks/{{task.id}}/remove'">Remove</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>
</div></div></div>
<script>

    function test_function() {
        let f = document.getElementById('show_active_label').onclick;
        document.getElementById('show_active_label').onclick = function(){f.call(); submit_form();};
    }

    function reformer(){
        alert('ololo')
        let f = document.getElementById('show_active_label').onclick;
        document.getElementById('show_active_label').onclick = function(){f.call(); submit_form();};
    }

    function submit_form(){
        document.getElementById("form").submit();
    }

</script>

{% endblock %}